[package]
name = "stm103"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { features = ["unproven"], version = "0.2.7" }
embedded-sdmmc = { path = "embedded-sdmmc-rs", default-features = false, features = ["defmt-log"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rtic = "1.1.4"
systick-monotonic = "1.0.1"
nb = "1"
bitflags = "2.2.1"
bytemuck = "1.13.1"
defmt = "0.3.4"
defmt-rtt = "0.4.0"
panic-probe = "0.3.1"

[patch.crates-io]
defmt = { git = "https://github.com/knurling-rs/defmt" }

[dependencies.stm32f1xx-hal]
version = "0.10.0"
features = ["stm32f103", "rt"]

[profile.release]
lto = true
strip = false

[workspace]
members = [
    "embedded-sdmmc-rs"
]